# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scratchmd < Formula
  desc "Sync local Markdown files with your CMS (Webflow, WordPress, etc)."
  homepage "https://github.com/whalesync/scratch-cli"
  version "0.3.25"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.3.25/scratchmd_darwin_amd64.tar.gz"
      sha256 "496dc4ef260603f6fec91b2f7f0e0754e27a889ff88bd6a67febc3d7e4dae501"

      define_method(:install) do
        bin.install "scratchmd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.3.25/scratchmd_darwin_arm64.tar.gz"
      sha256 "156630fd5f42a2caeae318dd4a8627072d8768dfc4dbdf2537c912686b7340e1"

      define_method(:install) do
        bin.install "scratchmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.3.25/scratchmd_linux_amd64.tar.gz"
      sha256 "d895130f78a88ec74140807418afb1ba3369140c19668d0c89a34e755021fbf9"
      define_method(:install) do
        bin.install "scratchmd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.3.25/scratchmd_linux_arm64.tar.gz"
      sha256 "af7dbd600b58b557eed042c20829f96d672b1bc19aca8b8e2008b9d351668690"
      define_method(:install) do
        bin.install "scratchmd"
      end
    end
  end

  test do
    system "#{bin}/scratchmd --version"
  end
end
