# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scratchmd < Formula
  desc "Sync local Markdown files with your CMS (Webflow, WordPress, etc)."
  homepage "https://github.com/whalesync/scratch-cli"
  version "0.3.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.3.9/scratchmd_darwin_amd64.tar.gz"
      sha256 "475bba4ee9d5f66b7011b8c4201a501a5129b24ad996feb19390a918a24a9903"

      def install
        bin.install "scratchmd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.3.9/scratchmd_darwin_arm64.tar.gz"
      sha256 "decf7a3685f5701ddf38ed34281a53f8e243571d6538268490dc0655825f42a3"

      def install
        bin.install "scratchmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.3.9/scratchmd_linux_amd64.tar.gz"
      sha256 "3e8a4b1b3989827c01bcfa36a0c86293ddac7b6bec23b5219770e33b4ddb96bc"
      def install
        bin.install "scratchmd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.3.9/scratchmd_linux_arm64.tar.gz"
      sha256 "f3a57f47ce961e20b36fe762325b690a45d4027474a62dec9e0fde7c78af60ff"
      def install
        bin.install "scratchmd"
      end
    end
  end

  test do
    system "#{bin}/scratchmd --version"
  end
end
