# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scratchmd < Formula
  desc "Sync local Markdown files with your CMS (Webflow, WordPress, etc)."
  homepage "https://github.com/whalesync/scratch-cli"
  version "0.3.37"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.3.37/scratchmd_darwin_amd64.tar.gz"
      sha256 "6100c66331b007d62f0f6e6665b1cff248847a8ceccdc5e3a4bd1a645abc1b48"

      define_method(:install) do
        bin.install "scratchmd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.3.37/scratchmd_darwin_arm64.tar.gz"
      sha256 "bfa8683c70033422e6d0b8f02e686460a878159fba5a6c536e5a2a474301c926"

      define_method(:install) do
        bin.install "scratchmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.3.37/scratchmd_linux_amd64.tar.gz"
      sha256 "df6bf7d4887ad0a4c466647154a00c37894f7b821901eafb3c993bd1dab928af"
      define_method(:install) do
        bin.install "scratchmd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.3.37/scratchmd_linux_arm64.tar.gz"
      sha256 "3456092d0e338791e771cd107b96ea25190cb2dee0746d248349ed09f3da0907"
      define_method(:install) do
        bin.install "scratchmd"
      end
    end
  end

  test do
    system "#{bin}/scratchmd --version"
  end
end
